Implementing string matching for DNA sequences

In [10]:
from Levenshtein import distance
import numpy as np
from utils import create_random_strand

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:


def lev_distance(a, b):
    # Wagner fisher algorithm

    c = np.zeros((len(a), len(b)), dtype=int)

    for i in range(len(a)):
        c[i, 0] = i

    for i in range(len(b)):
        c[0, i] = i


    for i in range(1, len(a)):
        for j in range(1, len(b)):

            subsitution_cost = 0 if a[i] == b[j] else 1

            c[i, j] = min(
                c[i-1, j-1] + subsitution_cost,
                c[i-1, j] + 1,
                c[i, j-1] + 1
            )

    return c[i, j], c



In [ ]:
def lev_distance_vec(a, b):
    # Wagner fisher algorithm

    c = np.zeros((len(a), len(b)), dtype=int)

    for i in range(len(a)):
        c[i, 0] = i

    for i in range(len(b)):
        c[0, i] = i

    scs = 


    for i in range(1, len(a)):
        for j in range(1, len(b)):

            subsitution_cost = 0 if a[i] == b[j] else 1

            c[i, j] = min(
                c[i-1, j-1] + subsitution_cost,
                c[i-1, j] + 1,
                c[i, j-1] + 1
            )

    return c[i, j], c


In [66]:
t = "AAACCAT"
s = "ACAT"

In [67]:
dis, mat = lev_distance(t, s)

In [68]:
mat

array([[0, 1, 2, 3],
       [1, 1, 1, 2],
       [2, 2, 1, 2],
       [3, 2, 2, 2],
       [4, 3, 3, 3],
       [5, 4, 3, 4],
       [6, 5, 4, 3]])

In [31]:
mat

array([[  0,   1,   2, ..., 227, 228, 229],
       [  1,   1,   2, ..., 226, 227, 228],
       [  2,   2,   2, ..., 225, 226, 227],
       ...,
       [127, 126, 125, ..., 131, 131, 131],
       [128, 127, 126, ..., 130, 131, 132],
       [129, 128, 127, ..., 130, 131, 131]])

In [33]:
base_lookup = {
    "A": 1,
    "C": 2,
    "G": 3,
    "T": 4
}

In [36]:
t_num = [base_lookup[i] for i in t]

In [40]:
s_num = np.array([base_lookup[i] for i in s])

In [38]:
t_num = np.array(t_num)

In [39]:
t_num

array([2, 1, 3, 1, 2, 3, 4, 4, 1, 4, 4, 2, 2, 3, 1, 4, 1, 2, 1, 2, 2, 4,
       3, 4, 4, 3, 1, 3, 3, 3, 4, 1, 1, 4, 3, 1, 3, 2, 3, 3, 2, 1, 3, 3,
       1, 1, 3, 2, 1, 3, 2, 3, 3, 1, 4, 2, 2, 3, 3, 1, 2, 2, 2, 3, 2, 4,
       1, 4, 1, 4, 2, 3, 2, 2, 4, 1, 2, 4, 4, 3, 1, 4, 1, 4, 2, 3, 3, 4,
       4, 4, 1, 4, 3, 3, 3, 1, 2, 3, 2, 3, 2, 3, 2, 2, 4, 2, 1, 2, 3, 1,
       4, 3, 4, 2, 2, 2, 1, 3, 3, 2, 4, 4, 2, 4, 3, 1, 4, 2, 3, 4])

In [41]:
s_num

array([2, 4, 2, 2, 1, 3, 4, 1, 4, 4, 2, 4, 2, 2, 1, 3, 3, 1, 3, 1, 4, 1,
       1, 1, 4, 4, 1, 1, 2, 3, 1, 4, 1, 1, 2, 4, 2, 4, 1, 1, 3, 1, 4, 3,
       2, 2, 3, 1, 1, 4, 2, 2, 3, 2, 4, 1, 1, 1, 4, 1, 2, 2, 1, 3, 3, 4,
       1, 1, 3, 3, 1, 3, 3, 3, 4, 2, 2, 2, 4, 3, 3, 4, 2, 2, 4, 1, 1, 4,
       1, 3, 2, 4, 1, 4, 1, 3, 2, 2, 3, 1, 1, 1, 1, 3, 2, 4, 1, 2, 2, 2,
       4, 1, 4, 3, 1, 1, 2, 1, 3, 2, 2, 1, 4, 1, 2, 4, 2, 2, 4, 2, 3, 4,
       4, 2, 3, 2, 2, 4, 3, 3, 1, 3, 3, 4, 1, 4, 3, 4, 4, 2, 4, 4, 4, 1,
       3, 2, 2, 1, 1, 4, 2, 1, 1, 3, 2, 1, 3, 2, 1, 3, 3, 4, 3, 3, 4, 3,
       1, 1, 3, 3, 4, 3, 1, 4, 2, 3, 4, 3, 3, 4, 1, 1, 4, 1, 4, 1, 2, 1,
       3, 4, 4, 4, 3, 3, 1, 4, 1, 4, 1, 2, 2, 3, 3, 1, 3, 4, 1, 3, 4, 2,
       3, 1, 2, 2, 1, 4, 3, 1, 3, 4])

In [42]:
i = 2

In [43]:
np.where(i == t_num, 0, 1)

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1])